# Generated by Django 4.1.7 on 2024-03-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_entry_discounted_price_alter_entry_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='additional_notes',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='entry',
            name='colour',
            field=models.CharField(blank=True, default='nero', max_length=20),
        ),
        migrations.AlterField(
            model_name='entry',
            name='size',
            field=models.CharField(blank=True, default='M', max_length=20),
        ),
    ]
