# Generated by Django 4.1.7 on 2024-03-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_entry_additional_notes_alter_entry_colour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
