# Generated by Django 5.0.3 on 2024-03-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_entry_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='additional_notes',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
